/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminFailuresRouteImport } from './routes/admin/failures'
import { Route as AdminPurchasesRouteImport } from './routes/admin/purchases'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ImagesSplatRouteImport } from './routes/images/$'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGenerationsIdRouteImport } from './routes/api/generations.$id'
import { Route as ApiSharedTokenRouteImport } from './routes/api/shared.$token'
import { Route as ApiWebhooksMayarSecretRouteImport } from './routes/api/webhooks/mayar.$secret'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFailuresRoute = AdminFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationsIdRoute = ApiGenerationsIdRouteImport.update({
  id: '/api/generations/$id',
  path: '/api/generations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedTokenRoute = ApiSharedTokenRouteImport.update({
  id: '/api/shared/$token',
  path: '/api/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMayarSecretRoute = ApiWebhooksMayarSecretRouteImport.update({
  id: '/api/webhooks/mayar/$secret',
  path: '/api/webhooks/mayar/$secret',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/credits': typeof CreditsRoute
  '/history': typeof HistoryRoute
  '/setup': typeof SetupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/failures': typeof AdminFailuresRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/images/$': typeof ImagesSplatRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/generations/$id': typeof ApiGenerationsIdRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/webhooks/mayar/$secret': typeof ApiWebhooksMayarSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/credits': typeof CreditsRoute
  '/history': typeof HistoryRoute
  '/setup': typeof SetupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/failures': typeof AdminFailuresRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/images/$': typeof ImagesSplatRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/generations/$id': typeof ApiGenerationsIdRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/webhooks/mayar/$secret': typeof ApiWebhooksMayarSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/credits': typeof CreditsRoute
  '/history': typeof HistoryRoute
  '/setup': typeof SetupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/failures': typeof AdminFailuresRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/images/$': typeof ImagesSplatRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/s/$token': typeof STokenRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/generations/$id': typeof ApiGenerationsIdRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/webhooks/mayar/$secret': typeof ApiWebhooksMayarSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/credits'
    | '/history'
    | '/setup'
    | '/admin/accounts'
    | '/admin/failures'
    | '/admin/purchases'
    | '/api/generate'
    | '/api/uploads'
    | '/images/$'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/s/$token'
    | '/account/'
    | '/admin/'
    | '/api/auth/$'
    | '/api/generations/$id'
    | '/api/shared/$token'
    | '/api/webhooks/mayar/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/credits'
    | '/history'
    | '/setup'
    | '/admin/accounts'
    | '/admin/failures'
    | '/admin/purchases'
    | '/api/generate'
    | '/api/uploads'
    | '/images/$'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/s/$token'
    | '/account'
    | '/admin'
    | '/api/auth/$'
    | '/api/generations/$id'
    | '/api/shared/$token'
    | '/api/webhooks/mayar/$secret'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/credits'
    | '/history'
    | '/setup'
    | '/admin/accounts'
    | '/admin/failures'
    | '/admin/purchases'
    | '/api/generate'
    | '/api/uploads'
    | '/images/$'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/s/$token'
    | '/account/'
    | '/admin/'
    | '/api/auth/$'
    | '/api/generations/$id'
    | '/api/shared/$token'
    | '/api/webhooks/mayar/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreditsRoute: typeof CreditsRoute
  HistoryRoute: typeof HistoryRoute
  SetupRoute: typeof SetupRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGenerationsIdRoute: typeof ApiGenerationsIdRoute
  ApiSharedTokenRoute: typeof ApiSharedTokenRoute
  ApiWebhooksMayarSecretRoute: typeof ApiWebhooksMayarSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/failures': {
      id: '/admin/failures'
      path: '/failures'
      fullPath: '/admin/failures'
      preLoaderRoute: typeof AdminFailuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generations/$id': {
      id: '/api/generations/$id'
      path: '/api/generations/$id'
      fullPath: '/api/generations/$id'
      preLoaderRoute: typeof ApiGenerationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared/$token': {
      id: '/api/shared/$token'
      path: '/api/shared/$token'
      fullPath: '/api/shared/$token'
      preLoaderRoute: typeof ApiSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mayar/$secret': {
      id: '/api/webhooks/mayar/$secret'
      path: '/api/webhooks/mayar/$secret'
      fullPath: '/api/webhooks/mayar/$secret'
      preLoaderRoute: typeof ApiWebhooksMayarSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminFailuresRoute: typeof AdminFailuresRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminFailuresRoute: AdminFailuresRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CreditsRoute: CreditsRoute,
  HistoryRoute: HistoryRoute,
  SetupRoute: SetupRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGenerationsIdRoute: ApiGenerationsIdRoute,
  ApiSharedTokenRoute: ApiSharedTokenRoute,
  ApiWebhooksMayarSecretRoute: ApiWebhooksMayarSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
